### ISSUE TITLE
요구한다.

### ISSUE THREAD

**Issue by gimhanul** [deepringing/ssom-server#5]
### ✨ Describe

안녕하세요 진유림개발자님 프론트엔드 개발자 김한울입니다. 다음 요구사항 신속하게 개발 바랍니다 ^^__

### ✅ Tasks

- [x] team에 member 추가하는 api
- [x] goal만드는 api가 team으로 만드는 것 밖에 없는데 user가 만드는 것도 해주세요
- [x] todo 만드는 api
- [x] todo 완료로 바꾸는 api

### 🙋🏻 More

생각날 때마다 추가할테니까 유의 ^__^
그리고 goal 쿼리해올 때 todo로 process 진행상황 백분율로 같이 넘겨주세요

**Comment by gimhanul** [comment]
- [x] goal 쿼리할 때 team 정보 추가해주세요 (member까지)
- [x] team 만들 때 현재 그냥 team만 save하고 있는데 **current user를 member로까지 만들어야 합니다**
- [x] team query할 때 그냥 전체 team 가져오는 것 같은데 current user로 멤버에서 한 번 타고 가서 가져와야댐니다
- [x] goal 만들 때 endDate 넣어주세요
- [x] todo 조회 (goal id로)
- [x] /goal/my 500 뜸
